apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evepraisal-db
  namespace: eve-corp
spec:
  storageClassName: glusterfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi